### ISSUE TITLE
is this a fork?

### ISSUE THREAD

**Issue by gabrielsroka** [mattmcnabb/Okta#15]
Hi @mattmcnabb ,

I was wondering if this is a fork of the official Okta PowerShell SDK.

Thanks,

Gabriel

**Comment by mattmcnabb** [comment]
@gabrielsroka this is not a fork of any project, but does leverage the Okta .Net SDK. As far as I'm aware, Okta doesn't have any official PowerShell support but does still have the legacy Okta.Core.Automation module available for those who would like to use it.

I've deliberated over the design of this module quite a bit and decided that the best way to go was to use the official SDK in order to keep in sync as closely as possible with features and capabilities. I hope this answers your question!
